apiVersion: v2
name: appflowy
description: AppFlowy Cloud Helm Chart
type: application
version: 0.0.1
dependencies:
  - name: valkey
    condition: valkey.enabled
    version: 0.9.3
    repository: https://valkey.io/valkey-helm/
  - name: appflowy-cloud
    condition: appflowy-cloud.enabled
    version: 0.1.0
  - name: appflowy-gotrue
    condition: appflowy-gotrue.enabled
    version: 0.1.0
  - name: appflowy-admin
    condition: appflowy-admin.enabled
    version: 0.1.0
  - name: appflowy-worker
    condition: appflowy-worker.enabled
    version: 0.1.0
  - name: appflowy-web
    condition: appflowy-web.enabled
    version: 0.1.0
  - name: appflowy-ai
    condition: global.ai.enabled
    version: 0.1.0
